### ISSUE TITLE
第十八期

### ISSUE THREAD

**Issue by azzgo** [ThoughtWorksInc/JS-Monthly-Chengdu#10]

**Comment by azzgo** [comment]
[Fluent Design](http://fluent.microsoft.com/)
An eloquent design system for a complex world

**Comment by azzgo** [comment]
speedracer
https://github.com/ngryman/speedracer

**Comment by azzgo** [comment]
https://github.com/Rich-Harris/butternut
The fast, future-friendly minifier

**Comment by azzgo** [comment]
[JSConf EU 2017 Video](https://www.youtube.com/playlist?list=PL37ZVnwpeshFmAPr65sU2O5WMs7_CGjs_)

**Comment by LeiZeng** [comment]
Nodejs 要发布8.0啦
https://medium.com/the-node-js-collection/node-js-8-0-0-has-been-delayed-and-will-ship-on-or-around-may-30th-cd38ba96980d

**Comment by LeiZeng** [comment]
Expo
React Native with fun

**Comment by LeiZeng** [comment]
WebAssembly
Javascript will no longer be the only language in browser

**Comment by LeiZeng** [comment]
Webpack 3.0 release!

**Comment by azzgo** [comment]
WebAssembly这个已经提过很多次了，我觉得配上 这个视频更好https://www.youtube.com/watch?v=HktWin_LPf4&index=4&list=PL37ZVnwpeshFmAPr65sU2O5WMs7_CGjs_
