### ISSUE TITLE
Issue 19

### ISSUE THREAD

**Issue by azzgo** [ThoughtWorksInc/JS-Monthly-Chengdu#11]
js-joda/js-joda https://js-joda.github.io/js-joda/

Immutable date and time library for javascript

**Comment by azzgo** [comment]
ESLint v4.0.0 released

http://eslint.org/blog/2017/06/eslint-v4.0.0-released

**Comment by azzgo** [comment]
https://ponyfoo.com/articles/tc39-ecmascript-proposals-future-of-javascript

了解下未来的JavaScript

**Comment by azzgo** [comment]
https://developers.google.com/web/updates/2017/06/headless-karma-mocha-chai

Automated testing with Headless Chrome

**Comment by azzgo** [comment]
https://github.com/nodejs/node-chakracore

**Comment by azzgo** [comment]
[NPX](https://medium.com/@maybekatz/introducing-npx-an-npm-package-runner-55f7d4bd282b)
Introducing npx: an npm package runner

**Comment by azzgo** [comment]
[New Features of ES8](https://hackernoon.com/es8-was-released-and-here-are-its-main-new-features-ee9c394adf66)

**Comment by LeiZeng** [comment]
https://native.directory/ 
Collection of popular react native packages

**Comment by azzgo** [comment]
[Rxjs By Example](https://www.youtube.com/watch?v=K7AvXUNB2X8)

**Comment by azzgo** [comment]
Karma-chrome-launcher
v2.2.0
Features

add ChromiumHeadless (7a12021)

CI，phantomjs的良好替代品

[Automated testing with Headless Chrome](https://developers.google.com/web/updates/2017/06/headless-karma-mocha-chai)

<https://github.com/angular/protractor/blob/master/docs/browser-setup.md#using-headless-chrome>

<https://github.com/graphcool/chromeless>

**Comment by LeiZeng** [comment]
https://github.com/gpujs/gpu.js
利用webGL优化高CPU利用率计算

**Comment by azzgo** [comment]
I think it is enough for close it.
