### ISSUE TITLE
二十一期

### ISSUE THREAD

**Issue by azzgo** [ThoughtWorksInc/JS-Monthly-Chengdu#13]

**Comment by azzgo** [comment]
https://github.com/ethanent/eucli

计算多维空间距离

**Comment by azzgo** [comment]
[Yarn 1.0](https://code.facebook.com/posts/274518539716230)
Release

**Comment by azzgo** [comment]
[react-powerplug](https://github.com/renatorib/react-powerplug)

**Comment by azzgo** [comment]
https://element-angular.faas.ele.me/guide/install

**Comment by LeiZeng** [comment]
https://facebook.github.io/react/blog/2017/09/26/react-v16.0.html
React v16 without Parent Patent.

**Comment by azzgo** [comment]
https://facebook.github.io/react/blog/2017/09/26/react-v16.0.html
React 16

**Comment by azzgo** [comment]
http://coffeescript.org/announcing-coffeescript-2/
Announcing  CoffeeScript 2

**Comment by azzgo** [comment]
https://hackernoon.com/angular-version-5-release-was-delayed-e7b5c26b0624
angular v5 delay

**Comment by azzgo** [comment]
https://medium.com/the-vue-point/upcoming-typescript-changes-in-vue-2-5-e9bd7e2ecf08

Upcoming TypeScript Changes in Vue 2.5

**Comment by LeiZeng** [comment]
https://github.com/graphcool/graphcool
Graphcool Framework Preview
