### ISSUE TITLE
第二十三期

### ISSUE THREAD

**Issue by azzgo** [ThoughtWorksInc/JS-Monthly-Chengdu#16]

**Comment by azzgo** [comment]
## Tech

美化滚动条 
https://alfred-sun.github.io/blog/2014/12/24/scrollbar-customized-with-css-style/

**Comment by azzgo** [comment]
## Repo
[Parcel](https://parceljs.org/)
Blazing fast, zero configuration web application bundler

**Comment by azzgo** [comment]
## Basic
[A different way of understanding this in JavaScript](http://2ality.com/2017/12/alternate-this.html)

**Comment by LeiZeng** [comment]
https://github.com/wekan/wekan
trello 开源复刻版。。。

**Comment by LeiZeng** [comment]
https://github.com/hql287/Manta 桌面应用解决方案

**Comment by azzgo** [comment]
[Fragments](https://reactjs.org/docs/fragments.html)
React 新特性，不需要为了添加一个列表展示的组件包裹一个不必要的节点啦

**Comment by azzgo** [comment]
https://github.com/Chalarangelo/30-seconds-of-code#readme

**Comment by azzgo** [comment]
[JS 现状调查](https://medium.freecodecamp.org/i-just-asked-23-000-developers-what-they-think-of-javascript-heres-what-i-learned-9a06b61998fa)

**Comment by azzgo** [comment]
[Angular 知识点汇总(2017)](https://malcoded.com/posts/angular-top-2017)

**Comment by azzgo** [comment]
@LeiZeng  Manta 怎么看是个应用呢，看起来是个用来开发票的程序
