### ISSUE TITLE
Issue 24

### ISSUE THREAD

**Issue by LeiZeng** [ThoughtWorksInc/JS-Monthly-Chengdu#18]

**Comment by azzgo** [comment]
https://github.com/sdras/object-explorer

便利的询问式查询 学习方式获取 object 方法

**Comment by JimmyLv** [comment]
https://github.com/the-road-to-learn-react/the-road-to-learn-react-chinese

~~最好的~~ React 中文学习资料 （2333……）

**Comment by LeiZeng** [comment]
https://github.com/hyperapp/hyperapp
比Vue还轻量级，1kb的前端应用框架

**Comment by azzgo** [comment]
(*ﾟДﾟ*) , 我以为之前引入过的，这个库之前玩的时候感觉用起来有点难用，个人意见，没有生态支持，(￣▽￣)~*，算是玩具

**Comment by LeiZeng** [comment]
是的，就是一个vue的初级版，生态基本为零；不妨碍我们放进来

**Comment by azzgo** [comment]
喜闻乐见的 全集类文章 https://medium.com/dailyjs/the-most-popular-javascript-links-of-2017-e4616e8b48c7

The most popular JavaScript links of 2017

**Comment by azzgo** [comment]
http://blog.npmjs.org/post/168978377570/new-package-moniker-rules

**Comment by JimmyLv** [comment]
[Tips to learn React + Redux in 2018 - RWieruch](https://www.robinwieruch.de/tips-to-learn-react-redux/)

**Comment by LeiZeng** [comment]
https://github.com/prettier/prettier

Code formatter for everything in front-end，你还在用jslint，csslint，eslint或者tslint，可以考虑换成一个了

**Comment by azzgo** [comment]
@LeiZeng 这个16期发过了 prettier

**Comment by LeiZeng** [comment]
哦，好
我用了一下感觉还可以哈，可以考虑在公司的项目推一推

**Comment by LeiZeng** [comment]
https://github.com/clauderic/react-sortable-hoc
非常通用的解决方案，集成简单，兼容性也很好。

**Comment by LeiZeng** [comment]
@azzgo 话说这个你之前是不是可以用上

**Comment by LeiZeng** [comment]
https://github.com/google/boardgame.io
全栈小游戏解决方案

**Comment by azzgo** [comment]
哈哈，找到的就是这个，已经用上了，挺好用的

**Comment by azzgo** [comment]
[Webpack 4 将会实现默认无配置模式](https://twitter.com/jdalton/status/951250082791227392)
Inspired by Parcel’s approach.

**Comment by azzgo** [comment]
https://github.com/bvaughn/react-virtualized

哈哈，终于找到一个前端优化列表性能的库了

**Comment by azzgo** [comment]
准备发一版 @LeiZeng ， 看下内容够不够呢

**Comment by LeiZeng** [comment]
发吧，哦，把我们翻译的React 学习之道放进来

**Comment by JimmyLv** [comment]
就是，😂 

对了，我们的 Monthly 有考虑对外发布么？

**Comment by LeiZeng** [comment]
可以吧，只是要考虑一下用什么渠道，你有想法吗

**Comment by azzgo** [comment]
@JimmyLv 必须的呢

**Comment by azzgo** [comment]
@LeiZeng 可以考虑 微信公众号 推送，+ 邮件推送
