### ISSUE TITLE
第二十六期

### ISSUE THREAD

**Issue by azzgo** [ThoughtWorksInc/JS-Monthly-Chengdu#23]

**Comment by LeiZeng** [comment]
https://medium.com/@tomastrajan/how-to-speed-up-continuous-integration-build-with-new-npm-ci-and-package-lock-json-7647f91751a

**Comment by lrrfantasy** [comment]
WebGL 3D Engine by Alibaba

https://github.com/alibaba/G3D

**Comment by LeiZeng** [comment]
https://reactjs.org/blog/2018/03/01/sneak-peek-beyond-react-16.html
性能提升，赶紧升级

**Comment by LeiZeng** [comment]
https://yarnpkg.com/blog/2017/08/02/introducing-workspaces/
更好的monorepo方案，比lerna快多了

**Comment by azzgo** [comment]
[Propel](https://github.com/propelml/propel)
JS 上的科学计算库

**Comment by LeiZeng** [comment]
https://github.com/jamiebuilds/react-loadable
异步code splitting方案

**Comment by azzgo** [comment]
[Rename flatten to smoosh ](https://github.com/tc39/proposal-flatMap/pull/56)
来看社区的一场撕逼现场

**Comment by azzgo** [comment]
[Mpvue](https://github.com/Meituan-Dianping/mpvue)
基于 Vue.js 的小程序开发框架，从底层支持 Vue.js 语法和构建工具体系

**Comment by LeiZeng** [comment]
https://github.com/staltz/prevent-smoosh @azzgo

**Comment by azzgo** [comment]
就是从这个库找到的，233

**Comment by LeiZeng** [comment]
确实挺逗的，笑死我了

**Comment by azzgo** [comment]
yarn 那个在 1.0 release 的时候有提到过
![image](https://user-images.githubusercontent.com/5636512/37269296-bad90354-2604-11e8-897b-fe7f2bceb710.png)

**Comment by LeiZeng** [comment]
嗯嗯

**Comment by azzgo** [comment]
[Sneak Peek: Beyond React 16](https://reactjs.org/blog/2018/03/01/sneak-peek-beyond-react-16.html)
With vast differences in computing power and network speed, how do we deliver the best user experience for everyone?
