### ISSUE TITLE
第二十七期

### ISSUE THREAD

**Issue by azzgo** [ThoughtWorksInc/JS-Monthly-Chengdu#25]

**Comment by azzgo** [comment]
[迁移到 Typescript](https://medium.com/unsplash/how-we-gradually-migrated-to-typescript-at-unsplash-7a34caa24ef1)
一步一步体验 Typescript

**Comment by azzgo** [comment]
[TensorFlow.js](https://js.tensorflow.org/)
前端同学，是时候跟一波机器学习潮流了

**Comment by azzgo** [comment]
[Redux not Dead Yet](http://blog.isquaredsoftware.com/2018/03/redux-not-dead-yet/)
React 新特性 Redux 死亡传言四起，But Redux 还能再战

**Comment by azzgo** [comment]
[React 16.3](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html)
React 新特性大招频繁，别怕，官方有迁移方法

**Comment by LeiZeng** [comment]
https://github.com/mrmartineau/design-system-utils
设计系统的theme工具库

**Comment by LeiZeng** [comment]
https://medium.com/npm-inc/announcing-npm-6-5d0b1799a905
NPM 杀回来了

**Comment by azzgo** [comment]
[Version 6 of Angular Now Available](https://blog.angular.io/version-6-of-angular-now-available-cc56b0efa7a4)
Angular 6 发布，Angular Element，ng library 等等新特性

**Comment by azzgo** [comment]
[Dayjs](https://github.com/xx45/dayjs)
2kb 的 Moment.js 兼容时间操作库
