### ISSUE TITLE
第十一期准备

### ISSUE THREAD

**Issue by LeiZeng** [ThoughtWorksInc/JS-Monthly-Chengdu#3]

**Comment by LeiZeng** [comment]
一键式react工程创建工具
https://github.com/facebookincubator/create-react-app

Isomophic react servere
https://github.com/redfin/react-server

**Comment by LeiZeng** [comment]
自动图片优化插件
https://github.com/Klathmon/imagemin-webpack-plugin

**Comment by azzgo** [comment]
Angular2教程： http://courses.angularclass.com/

**Comment by azzgo** [comment]
Fiber算法：https://github.com/acdlite/react-fiber-architecture

**Comment by WillXing** [comment]
webpack图表输出webpack-dashboard
https://github.com/FormidableLabs/webpack-dashboard

**Comment by LeiZeng** [comment]
Nodejs authentication tool
https://github.com/jaredhanson/passport
