### ISSUE TITLE
第三十期

### ISSUE THREAD

**Issue by azzgo** [ThoughtWorksInc/JS-Monthly-Chengdu#30]

**Comment by azzgo** [comment]
[Pollyjs](https://github.com/Netflix/pollyjs)
为 HTTP 打桩（Stub）

**Comment by azzgo** [comment]
[Flexbugs](https://github.com/philipwalton/flexbugs)
Flex 布局 Bug 问题及解决方案集锦

**Comment by azzgo** [comment]
[Class Validator](https://github.com/typestack/class-validator)
基于 Typescript 的验证器，试试吧

**Comment by azzgo** [comment]
[Beaker](https://github.com/beakerbrowser/beaker)
发布你的网站，without a server

**Comment by azzgo** [comment]
[JSConf in EU](https://www.youtube.com/watch?v=SV-cgdobtTA&list=PL37ZVnwpeshG2YXJkun_lyNTtM-Qb3MKa)
JSConf 欧洲视频集锦

**Comment by azzgo** [comment]
[Babel Time Runtime](https://github.com/babel/babel-time-travel)
Babel 时间旅行，让你看看 Babel 编译过程

**Comment by azzgo** [comment]
[Redux vs. The React Context API](https://daveceddia.com/context-api-vs-redux/)
看看 React 新的 Context API 都干了啥吧，选型必备

**Comment by azzgo** [comment]
[Nodejs 23 项安全清单](https://medium.com/@nodepractices/were-under-attack-23-node-js-security-best-practices-e33c146cb87d)
开发 Nodejs 必备安全清单，防患于未然

**Comment by azzgo** [comment]
[移除 Stage Presets](https://babeljs.io/blog/2018/07/27/removing-babels-stage-presets)
Babel 准备干掉 Stage，并作出一些调整，值得关注

**Comment by azzgo** [comment]
[Apexcharts](https://github.com/apexcharts/apexcharts.js)
为啥又来一个图表库，看下[文章](https://medium.com/@juned.chhipa/bridging-the-gap-between-low-level-and-high-level-charting-libraries-a8f6c1819ba5)了解来由

**Comment by SBeator** [comment]
[Typescript 3.0](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-0.html)
Typescript 3.0 发布了，快来看看有什么新特性吧
