### ISSUE TITLE
第三十一期

### ISSUE THREAD

**Issue by SBeator** [ThoughtWorksInc/JS-Monthly-Chengdu#31]

**Comment by lijinke666** [comment]
[regexper](https://regexper.com/#%2F%5E%5Cd(%3F%3D%5Cw)%7B3%2C10%7D%24%2F)
图形化正则表达式

**Comment by lijinke666** [comment]
[Web Push](https://fed.renren.com/2017/10/08/service-worker-notification/)
用Service Worker 本地 push 消息 骚的一匹

**Comment by lijinke666** [comment]
[怎么写Bug](https://zhuanlan.zhihu.com/p/29521210)
快速入门如何写出不可维护的代码

**Comment by Caraws** [comment]
[Practical CSS Scroll Snapping](https://css-tricks.com/practical-css-scroll-snapping/)
CSS `Scroll Snapping` 处理滚动

**Comment by azzgo** [comment]
[Vue CLI 3.0](https://mp.weixin.qq.com/s/hfr2Q3FXZFIdqM_r8HrLwQ)
重磅！Vue CLI 3.0正式发布，带来多项重大更新

**Comment by azzgo** [comment]
[通用传感器 API 介绍](https://mobiforge.com/design-development/the-generic-sensor-api)
看看新提案，不是个坏事

**Comment by azzgo** [comment]
[Size Plugin](https://github.com/GoogleChromeLabs/size-plugin)
给你的 Bundle Size 也做个diff

**Comment by azzgo** [comment]
[Babel 7 Released](https://babeljs.io/blog/2018/08/27/7.0.0)
Babel 7 发布了，整合命名空间、增加 js 配置文件等等新特性，快来看看吧

**Comment by azzgo** [comment]
[GraphQL Server Tutorial with Apollo Server and Express](https://www.robinwieruch.de/graphql-apollo-server-tutorial/)
一份 GraphQL 搭建指南，都 8012 年了，不看就落伍啦

**Comment by azzgo** [comment]
[Life of a Pixel](https://mp.weixin.qq.com/s/87OYpou4ynpvYlcExEO40w)
让你更透彻地理解浏览器是如何工作的

**Comment by SBeator** [comment]
[中文 DOS 游戏](https://github.com/rwv/chinese-dos-games)
在浏览器中游玩中文 DOS 游戏
