### ISSUE TITLE
第三十二期

### ISSUE THREAD

**Issue by azzgo** [ThoughtWorksInc/JS-Monthly-Chengdu#33]

**Comment by azzgo** [comment]
[Watermelon DB](https://github.com/Nozbe/WatermelonDB)
React 和 React Native 下一代数据库

**Comment by azzgo** [comment]
[Nlp.js](https://github.com/axa-group/nlp.js)
Node 版本的 NLP

**Comment by azzgo** [comment]
[Service Worker Cookbook](https://serviceworke.rs/)
Sw 的菜谱，你喜欢哪一道？

**Comment by SBeator** [comment]
[33-js-concepts](https://github.com/leonardomso/33-js-concepts) [(中文版)](https://github.com/stephentian/33-js-concepts)
📜 33 concepts every JavaScript developer should know. (📜 每个 JavaScript 工程师都应懂的33个概念)

**Comment by azzgo** [comment]
[Vue 前瞻](https://medium.com/vue-mastery/evan-you-previews-vue-js-3-0-ab063dec3547)
尤雨溪带你了解 3.0 新特性

**Comment by azzgo** [comment]
[The Power of Web Components](https://hacks.mozilla.org/2018/11/the-power-of-web-components/)
Web Components 给 Web 更多的想象力

**Comment by azzgo** [comment]
[Slate](https://github.com/ianstormtaylor/slate)
一款可以自定义的富文本编辑器

**Comment by azzgo** [comment]
[Handling Errors in JavaScript: The Definitive Guide](https://levelup.gitconnected.com/the-definite-guide-to-handling-errors-gracefully-in-javascript-58424d9c60e6)
JavaScript 中错误处理的一份小册，值得参考

**Comment by azzgo** [comment]
[Common Testing Mistakes](https://blog.kentcdodds.com/common-testing-mistakes-1a3d2d209f0)
单元测试中常犯的错误，记下小本本
