### ISSUE TITLE
第 43 期

### ISSUE THREAD

**Issue by lijinke666** [ThoughtWorksInc/JS-Monthly-Chengdu#45]

**Comment by lijinke666** [comment]
[AbortController](https://developer.mozilla.org/zh-CN/docs/Web/API/FetchController)
使用 `new AbortController()` 实现 fetch 的 abort 功能

**Comment by lijinke666** [comment]
[unlock-music](https://github.com/ix64/unlock-music)
在浏览器中解锁加密的音乐文件, 如解密网易云音乐

**Comment by lijinke666** [comment]
[fre](https://github.com/yisar/fre)
一个乞丐版的 React hook 实现, 可以学习作者的实现思路

**Comment by lijinke666** [comment]
[antd-dayjs-webpack-plugin](https://github.com/ant-design/antd-dayjs-webpack-plugin)
一个替换 moment.js 为 day.js 的 webpack 插件

**Comment by mutoe** [comment]
[github-annual-report](https://github.com/guanpengchn/github-annual-report)
快来查看你的专属 GitHub 2019 年度报告吧!

**Comment by mutoe** [comment]
[leetcode-editor](https://github.com/shuzijun/leetcode-editor)
在 Intellij 家族编辑器中快乐的刷 leetcode 的插件
