### ISSUE TITLE
十三期

### ISSUE THREAD

**Issue by azzgo** [ThoughtWorksInc/JS-Monthly-Chengdu#5]

**Comment by WillXing** [comment]
微信小应用可以上榜吗？

**Comment by azzgo** [comment]
vue2.0 realease

**Comment by azzgo** [comment]
PWA Dev Summit 2016, https://www.youtube.com/playlist?list=PLlSjuqJVmEfqQTqWcs4xyWwuXrcn3mTZL

**Comment by LeiZeng** [comment]
有实力取代NPM的包管理工具
https://github.com/yarnpkg/yarn/

**Comment by LeiZeng** [comment]
Free and reliable audio calls for everyone w/ browser p2p
https://github.com/mikeal/roll-call

**Comment by azzgo** [comment]
TypeScript 2.0 is now available!
