### ISSUE TITLE
第十六期

### ISSUE THREAD

**Issue by LeiZeng** [ThoughtWorksInc/JS-Monthly-Chengdu#8]

**Comment by LeiZeng** [comment]
[Sinopia](https://github.com/rlidwka/sinopia)
纯JS+文件系统搭建Private NPM

**Comment by azzgo** [comment]
[es6后时代的正则表达式](https://ponyfoo.com/articles/regular-expressions-post-es6?utm_source=javascriptweekly&utm_medium=email)
更好更强大的正则表达式来了

**Comment by azzgo** [comment]
[Chrome 代码覆盖率特性](https://blog.logrocket.com/using-the-chrome-devtools-new-code-coverage-feature-ca96c3dddcaf)
Chrome Devtools推出代码覆盖率特性,强大

**Comment by azzgo** [comment]
https://github.com/Lucifier129/factor-network
机器学习的东西，不太懂

**Comment by azzgo** [comment]
[Angular4](http://angularjs.blogspot.com/2017/03/angular-400-now-available.html?utm_source=javascriptweekly&utm_medium=email)
Angular4 Released，更好的AOT和Server Render支持

**Comment by azzgo** [comment]
[Prettier](http://jlongster.com/prettier-1.0?utm_source=javascriptweekly&utm_medium=email)
可配置的代码格式化工具

**Comment by azzgo** [comment]
[Next.js 2.0](https://zeit.co/blog/next2?utm_source=nodeweekly&utm_medium=email)
Next 2.0, 全面优化，全家桶式的React服务端渲染解决方案

**Comment by azzgo** [comment]
[The Basics of DOM Manipulation in Vanilla JavaScript (No jQuery)](https://www.sitepoint.com/dom-manipulation-vanilla-javascript-no-jquery/?utm_source=javascriptweekly&utm_medium=email)
Vanilla.js操作DOM指南
